### ISSUE TITLE
Crash drawing a collected Hypersian Rug in some geometries

### ISSUE THREAD

**Issue by jruderman** [zenorogue/hyperrogue#254]
./hyper -geo 4x5 -gp 2 0 -I "Hypersian Rug" 1

crashes in `hr::queuepolyat` due to the argument `h` being a null reference:

```
  * frame #0: 0x0000000100658e14 hyper`hr::queuepolyat(V=0x00007ffeefbfa8a0, h=0x0000000000000000, col=4292149503, prio=DEFAULT) at drawing.cpp:2512:37
    frame #1: 0x0000000100627fc6 hyper`hr::draw_shapevec(c=0x0000000000000000, V=0x00007ffeefbfa8a0, shv=size=0, col=4292149503, prio=DEFAULT) at floorshapes.cpp:985:18
    frame #2: 0x000000010062841f hyper`hr::draw_floorshape(c=0x0000000000000000, V=0x00007ffeefbfa8a0, fsh=0x000000010d554e60, col=4292149503, prio=DEFAULT) at floorshapes.cpp:1024:3
    frame #3: 0x00000001009bf5ee hyper`hr::drawItemType(it=itPalace, c=0x0000000000000000, V=0x00007ffeefbfc488, icol=6297600, pticks=2202, hidden=false) at graph.cpp:946:7
    frame #4: 0x0000000100933f6f hyper`hr::displayglyph(cx=1100, cy=66, buttonsize=44, glyph='?', color=8396800, qty=1, flags=129, id=51) at hud.cpp:231:7
    frame #5: 0x0000000100934958 hyper`hr::displayglyph2(cx=1100, cy=66, buttonsize=44, i=51) at hud.cpp:282:6
    frame #6: 0x0000000100937287 hyper`hr::drawStats() at hud.cpp:564:7
    frame #7: 0x00000001009f3d18 hyper`hr::normalscreen() at graph.cpp:5332:69
    frame #8: 0x00000001000562f3 hyper`hr::function_state<void (*)(), void>::call(this=0x0000000103914de0) const at hyper_function.h:23:16
    frame #9: 0x000000010022a438 hyper`hr::function<void ()>::operator(this=0x0000000103914dd0)() const at hyper_function.h:56:22
    frame #10: 0x00000001009f455f hyper`hr::drawscreen() at graph.cpp:5441:3
    frame #11: 0x000000010092baa2 hyper`hr::mainloopiter() at control.cpp:774:7
    frame #12: 0x000000010092d83d hyper`hr::mainloop() at control.cpp:1227:24
    frame #13: 0x0000000100afd8dd hyper`hr::hyper_main(argc=9, argv=0x0000000103917ee0) at hyper-main.cpp:64:3
```

This crash can also be reproduced using menus instead of command line: in "experiment with geometry" set tiling to "{5,4}" and variation to "expanded", then use cheat-overiew to gain a hypersian rug.

**Comment by zenorogue** [comment]
This commandline seems to work for me. Maybe it was fixed in the meantime?

**Comment by jruderman** [comment]
The commandline still crashes for me (ed1a1dc37cf747ab49181545227a85b672974513 on macOS).

If you want, I can catch it in lldb and we can look at it together on Discord.

**Comment by zenorogue** [comment]
Thanks, should be fixed now (it crashed for me too, but I was testing in a small window which did not show the items from other lands).
